### ISSUE TITLE
Question: Why only Vulkan

### ISSUE THREAD

**Issue by schell** [philpax/wgpu-openxr-example#8]
First of all thank you for this great example! 

It's early in my reading but I'm wondering why not let `wgpu` choose the underlying device and then write a `TryFrom` impl or similar for the openxr state. Bear in mind I'm still skimming this repo and have not yet grokked it. Essentially, why go from openxr to wgpu instead of the other way around?

**Comment by schell** [comment]
Of now I see in the readme this is all planned for the future, so I'm guessing the answer to this question is "time constraints", lol. Thanks again :)

**Comment by philpax** [comment]
Great question! OpenXR needs to be the one to provide the device - there's no way to convert a wgpu device to an OpenXR device - so you have to individually support each API in the bridge.

I've not supported the other APIs as I only needed Vulkan for my use case, but I'd be happy to help someone implement the other APIs as required :)

**Comment by schell** [comment]
Thank you!
